server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reader_db
    username: root
    password: your_password
  
  security:
    jwt:
      secret: your-secret-key-here-must-be-at-least-32-chars
      expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.reader: DEBUG

aliyun:
  sms:
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    sign-name: YourSignName
    template-code: SMS_XXXXXXXX