server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reader_db
    username: root
    password: your_password
  security:
    jwt:
      secret: 5426535
      access-token-expiration: 3600000  # 1小时
      refresh-token-expiration: 2592000000  # 30天
      issuer: reader-admin
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.reader: DEBUG

aliyun:
  sms:
    access-key-id: 3213211
    access-key-secret: 54353453
    sign-name: YourSignName
    template-code: SMS_XXXXXXXX

app:
  mail:
    from: your-email@example.com